### Guhnoo Yun, 2019010823 

In [1]:
import torch 
import torch.nn as nn 

we implement the forward computation of the pooling layer in the ```pool2d``` function.

In [3]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i: i + p_h, j: j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
    return Y

We can construct the input array X in the above diagram to validate the output of the two-dimensional maximum pooling layer.

In [5]:
X = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]], dtype=torch.float32)

pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

At the same time, we experiment with the average pooling layer.

In [6]:
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

***

* Padding and Stride <br/>
* construct an input data of shape ($1$, $1$, $4$, $4$), where the first two dimensions are batch and channel

In [7]:
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
print(X)

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])


We will demonstrate the use of padding and stride in the pooling layer through the two-dimensional maximum pooling layer ```MaxPool2d``` in the ```torch.nn module```. <br/>

we use a pooling window of shape ($3$, $3$), so we get a stride shape of ($3$, $3$) by default.

In [11]:
"""
Because there are no model parameters in the pooling layer, we do not need
to call the parameter initialization function
"""

pool2d = nn.MaxPool2d(3)  # 3x3 MaxPool

pool2d(X)

tensor([[[[10.]]]])

The stride and padding can be manually specified.

In [12]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

***

* Multiple Channels 

the pooling layer pools each input channel separately, rather than adding the inputs of each channel by channel as in a convolutional layer. 

In [13]:
X = torch.cat((X, X + 1), dim=1)
print(X)

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])


As we can see, the number of output channels is still 2 after pooling.

In [14]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])